# Site settings
title: My Journey in Data Science
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Enthusiast of all things tech, data, media, travel, food, and much more!
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tiffanytywu
github_username:  tiffanytwu
linkedin_username:  tiffanytywu
instagram_username: tiffanytwu
facebook_username: tiffanytywu

# Build settings
markdown: kramdown
